import React from 'react'
import Head from 'next/head'

import '../styles/globals.scss'
import '../styles/landing.scss'
import '../styles/tech.scss'
import '../styles/projects.scss'
import '../styles/contact.scss'


function MyApp({ Component, pageProps }) {
  return (
  <>
    {/* <Head>
        <title>Portfolio Julien Féger</title>
        <meta name="showcase of my projects" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head> */}
    <Component {...pageProps} />
  </>
  )
}

export default MyApp
