import Head from 'next/head'
import Image from 'next/image'
import Logo from '../components/logo'
import Section from '../components/section'

import { useState, useRef, useEffect } from 'react'

import Angular from '../public/angular.svg';
import Git from '../public/git.svg';
import Gitlab from '../public/gitlab.svg';
import Jira from '../public/jira.svg';
import Mongo from '../public/mongodb.svg';
import Node from '../public/nodejs.svg';
import ReactLogo from '../public/react.svg';
import Typescript from '../public/typescript.svg';

import data from '../data/realisations.json';
import GridProject from '../components/gridProjects';

export default function Landing() {

  const [projectsSectionHeight, setProjectsSectionHeight] = useState([])
  const [scrollPos, setScrollPos] = useState(0)
  const containerRef = useRef(null)

  useEffect(()=>{
    window.addEventListener('scroll', (e: any)=>{setScrollPos(window.scrollY)})
    return  window.removeEventListener('scroll', ()=>{console.log('scroll listener removed')})
  }, [])

  return (
    <div ref={containerRef}>
      {/* <Head>
        <title>Portfolio Julien Féger</title>
        <meta name="showcase of my projects" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Section name='Landing'>
        <div className='LandingCardWrapper' style={{top: scrollPos / 4}}>
          <h1 className='LandingCardWrapper-topCard-title'>Julien Féger</h1>
          <h2 className='LandingCardWrapper-topCard-subtitle'>Design & code</h2>
        </div>
        <div className='LogoWrapper' style={{bottom: `calc(5% + ${scrollPos / 3 }px)`}}>
          <Logo className='logo'/>
        </div>
        <div className='MaskedBorder'>
          <div className='MaskedBorder-frame'></div>
        </div>
      </Section>
      <Section name='Tech'>
        <div className='Tech-text-wrapper'>
          <em className='Tech-text'>Creativity<span className="special-colorizing">X</span>Technique</em>
        </div>
        <div className='Tech-wheel-wrapper'>
          <div className="Tech-wheel">
            <div className="angular-logo-wrapper">
                <Angular height={250} />
            </div>
            <div className="jira-logo-wrapper">
                <Jira height={250} />
            </div>
            <div className="git-logo-wrapper">
                <Git />
            </div>
            <div className="gitlab-logo-wrapper">
                <Gitlab />
            </div>
            <div className="node-logo-wrapper">
                <Node />
            </div>
            <div className="mongo-logo-wrapper">
                <Mongo height={250} />
            </div>
            <div className="react-logo-wrapper">
                <ReactLogo />
            </div>
            <div className="typescript-logo-wrapper">
                <Typescript />
            </div>
          </div>
        </div>
        <div className='MaskedBorder'>
          <div className='MaskedBorder-frame opposite-color'></div>
        </div>
      </Section>
      <Section name='Projects' style={{height: Math.max(...projectsSectionHeight) + 150}}>
          <GridProject getHeight={(heights)=>setProjectsSectionHeight(heights)} />
      </Section>
      <Section name='Contact' style={{position: 'relative'}}>
        <div className='MaskedBorder'>
          <div className='MaskedBorder-frame opposite-color'></div>
        </div>
      </Section>
    </div>
  )
}
